#!/bin/bash
#
# docker template for MYSQL
# Username: root
# Password: test (configured below via -e MYSQL_ROOT_PASSWORD=test)
# Hostname: localhost
# Port: 3306 (configured below via -p 3306:3306)

#Functions
dockermysql() {
	# @description create a docker container for MySQL
	# @param $1 available commands listed in usages
	# @param $... additional parameters based on inital command used
	# @output varies, depending on the command used

	local dockerimage="mysql:5.7"
	local containername="ldt_mysql"
	local containercmd="--character-set-server=utf8 --collation-server=utf8_general_ci --max_allowed_packet=50M --innodb-log-file-size=250M"
	local containeroptions=(
		"-e MYSQL_ROOT_PASSWORD=test"
		"-p 3306:3306"
	)

	if [ -n "$1" ]; then
		case "$1" in
			'recreate'|'run'|'start')
				dockercontainer "$1" "${containername}" "${dockerimage}" "${containercmd}" "${containeroptions[@]}";;
			*)
				dockercontainer "$1" "${containername}" "${@:2:${#}}";;
		esac
	else
		echo "Usage: ${FUNCNAME[0]} {$(usage_options_formatted ${dockercontainer_options[@]} ${dockerbasecontainer_options[@]})}"
	fi
}

init_dockercontainer() {
	# @description source dockercontainer to make it's functions available
	# @output None

	local repodir="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && git rev-parse --show-toplevel)"
	local scriptpath="${repodir}/docker/dockercontainer"

	if [ -f "${scriptpath}" ]; then
		. ${scriptpath}
	else
		echo "Error: Could not load dockercontainer"
		exit 1
	fi
}

#Main
init_dockercontainer

if [ "$0" = "${BASH_SOURCE}" ]; then
	dockermysql "${@}"

	exit $?
fi