# All cluster rights
# All operations on all indices
admin:
  cluster:
    - all
  indices:
    - names: '*'
      privileges:
        - all

# Monitoring cluster privileges
# All operations on all indices
power_user:
  cluster:
    - monitor
  indices:
    - names: '*'
      privileges:
        - all

# Only read operations on indices
user:
  indices:
    - names: '*'
      privileges:
        - read

# Only read operations on indices named events_*
events_user:
  indices:
    - names: 'events_*'
      privileges:
        - read
