#!/bin/bash
#
# Wrapper for docker

#Global Variables
dockercontainer_options=('recreate' 'run' 'start')

#Core Function
dockercontainer() {
	# @description used for managing docker containers
	# @param $1 container name
	# @param $2 available docker commands listed: dockerbasecontainer_options*
	# @param $... additional parameters based on docker command used
	# @output varies, depending on the command used

	if [ -n "$1" ] && [ -n "$2" ]; then
		case "$1" in
			'recreate')
				if (dockercontainer exists "$2"); then
					dockerbasecontainer rm "$2"
				fi

				dockercontainer run "${@:2:${#}}"

				return;;
			'run')
				local args_str="${@:5:${#}}"

				# Preserve forward slashes for escaped characters
				local cmd_args=${args_str//\\/\\\\}

				# Preserve single quotes
				cmd_args=${cmd_args//\'/\\\'}

				# Craft docker command to better handle command options with single quotes
				local cmd="$(echo docker run --name "$2" ${cmd_args} -d "$3" $4 | xargs)"

				bash -c "${cmd}"
				return;;
			'start')
				if (! dockerbasecontainer exists "$2"); then
					dockercontainer run "${@:2:${#}}"
				else
					dockerbasecontainer "$1" "$2"
				fi

				return;;
			*)
				dockerbasecontainer "${@}"
				return;;
		esac
	fi

	echo "Usage: ${FUNCNAME[0]} ($(dockerutil usage_options_formatted $(dockerbasecontainer dockerbasecontainer_options))) <container-name>"
	echo "Usage: ${FUNCNAME[0]} ($(dockerutil usage_options_formatted $(dockerbasecontainer dockerbasecontainer_options_exec))) <container-name> [-d] <command>"
	echo "Usage: ${FUNCNAME[0]} ($(dockerutil usage_options_formatted ${dockercontainer_options[@]})) <container-name> <docker-image> <container-command>"
}

#External Functions
dockerbasecontainer() {
	# @description reference dockerbasecontainer to utilize it's functions
	# @output None

	local repodir="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && git rev-parse --show-toplevel)"
	local scriptpath="${repodir}/docker/dockerbasecontainer"

	if [ -f "${scriptpath}" ]; then
		${scriptpath} "$@"
	else
		echo "Error: Could not load dockerbasecontainer"
		return 1
	fi
}

dockerutil() {
	# @description reference dockerutil to utilize it's functions
	# @output None

	local repodir="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && git rev-parse --show-toplevel)"
	local scriptpath="${repodir}/docker/dockerutil"

	if [ -f "${scriptpath}" ]; then
		${scriptpath} "$@"
	else
		echo "Error: Could not load dockerutil"
		return 1
	fi
}

verify_external_functions() {
	# @description check if external functions can be loaded, or else exit the script
	# @output None

	if !(dockerbasecontainer > /dev/null); then dockerbasecontainer; exit 1; fi
	if !(dockerutil > /dev/null); then dockerutil; exit 1; fi
}

#Main
if [ "$0" = "${BASH_SOURCE}" ]; then
	verify_external_functions

	case "$1" in
		'dockercontainer_options')
			echo ${dockercontainer_options[@]};;
		*)
			dockercontainer "${@}"
	esac

	exit $?
fi