#!/bin/bash
#
# Util functions for docker

#Global Variables

#Core Function
dockerutil() {
	case "$1" in
		'array_to_string_delimited')
			array_to_string_delimited "${@:2:${#}}";;
		'array_sorted_unique')
			array_sorted_unique "${@:2:${#}}";;
		'usage_options_formatted')
			usage_options_formatted "${@:2:${#}}";;
		*)
			array_to_string_delimited
			array_sorted_unique
			usage_options_formatted;;
	esac
}

#Functions
array_to_string_delimited() {
	# @description output array as a string, with delimiter as the separator
	# @description reference: https://superuser.com/a/720157
	# @param $1 delimiter 
	# @param $2 array
	# @output string output of the array, with delimiter as the separator

	if [ $# -ge 2 ] ; then
		local delimiter="$1"
		local array=("${@:2:${#}}")

		echo $(awk -v sep="$delimiter" '
			BEGIN{
				ORS=OFS="";
				for(i=1;i<ARGC;i++){
					arg=ARGV[i];
					print arg,ARGC-i-1?sep:""
				}
			}' "${array[@]}")
	else
		echo "Usage: $(basename $0) ${FUNCNAME[0]} <delimiter> <array[@]>"
	fi
}

array_sorted_unique() {
	# @description used to sort and remove duplicates from the provided array
	# @description reference: https://superuser.com/a/720157
	# @param $1 array
	# @output string output of the array, sorted and without duplicates

	if [ "${#@}" -gt 0 ]; then
		printf '%s\n' "${@}" | sort -u
	else
		echo "Usage: $(basename $0) ${FUNCNAME[0]} <array>"
	fi
}

usage_options_formatted() {
	# @description used to format usage options for consistency and readability
	# @param $1 usage options array
	# @output string output of the Usage statement, formatted
	
	if [ $# -ge 1 ] ; then
		array_to_string_delimited "|" $(array_sorted_unique "${@}")
	else
		echo "Usage: $(basename $0) ${FUNCNAME[0]} <usage-options-array>"
	fi
}

#Main
if [ "$0" = "${BASH_SOURCE}" ]; then
	dockerutil "${@}"

	exit $?
fi