#!/bin/bash
#
# docker template for Elasticsearch
# Hostname: localhost
# Port: 9200 (configured via -p 9200:9200)

#Functions
dockerelasticsearch() {
	# @description create a docker container for Elasticsearch
	# @param $1 available commands listed in usages
	# @param $... additional parameters based on inital command used
	# @output varies, depending on the command used

	local dockerimage="elasticsearch:2.4.4"
	local containername="ldt_elasticsearch"
	local containercmd=""
	local containeroptions=(
		"-p 9200:9200"
		"-p 9300:9300"
	)

	local elasticsearch_options=(
		"cluster.name: LiferayElasticsearchCluster"
		"network.host: 0.0.0.0"
		"http.cors.enabled: true"
		"http.cors.allow-origin: \"*\""
		"http.cors.allow-headers: \"X-Requested-With, Content-Type, Content-Length, X-User\""
	)

	local elasticsearch_options_delimited="$(array_to_string_delimited '\\n' "${elasticsearch_options[@]}")"

	if [ -n "$1" ]; then
		case "$1" in
			'recreate'|'run'|'start')
				local init_elastic

				if [ "$1" == 'recreate' ] || (! dockercontainer 'exists' "${containername}"); then
					init_elastic=1
				fi

				dockercontainer "$1" "${containername}" "${dockerimage}" "${containercmd}" "${containeroptions[@]}"

				if [ "${init_elastic}" == "1" ]; then
					dockercontainer exec "${containername}" bash -c 'awk -v options="'"${elasticsearch_options_delimited//\"/\\\"}"'" '\''BEGIN{print options}'\'' > /usr/share/elasticsearch/config/elasticsearch.yml'

					dockerelasticsearch 'restart'
				fi;;
			*)
				dockercontainer "$1" "${containername}" "${@:2:${#}}";;
		esac
	else
		echo "Usage: ${FUNCNAME[0]} {$(usage_options_formatted ${dockercontainer_options[@]} ${dockerbasecontainer_options[@]})}"
	fi
}

init_dockercontainer() {
	# @description source dockercontainer to make it's functions available
	# @output None
	
	local repodir="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && git rev-parse --show-toplevel)"
	local scriptpath="${repodir}/docker/dockercontainer"

	if [ -f "${scriptpath}" ]; then
		. ${scriptpath}
	else
		echo "Error: Could not load dockercontainer"
		exit 1
	fi
}

#Main
init_dockercontainer

if [ "$0" = "${BASH_SOURCE}" ]; then
	dockerelasticsearch "${@}"

	exit $?
fi