#!/bin/bash
#
# docker template for OpenLDAP
# host: localhost
# port: 10389 (configured via -p 10389:389)
# 
# bind DN/User: cn=admin,dc=example,dc=org (configured via -e SLAPD_DOMAIN=example.org + default user: admin)
# bind Password: admin (configured via -e SLAPD_PASSWORD=admin)
#
# Preconfigured for Liferay
#     Prepopulate using ldif files in folder: prepopulate
# ldif files:
#     ./prepopulate/prepopulate.ldif
#         Generates a password policy
#         Generates test users

#Core Function
dockeropenldap() {
	# @description create a docker container for OpenLDAP
	# @param $1 available commands listed in usages
	# @param $... additional parameters based on inital command used
	# @output varies, depending on the command used

	local dockerimage="dinkel/openldap"
	local containername="ldt_openldap"
	local containercmd=""
	local containeroptions=(
		"-v $(dirname ${BASH_SOURCE[0]})/prepopulate:/etc/ldap.dist/prepopulate"
		"-e SLAPD_PASSWORD=admin"
		"-e SLAPD_CONFIG_PASSWORD=admin"
		"-e SLAPD_DOMAIN=example.org"
		"-e SLAPD_ADDITIONAL_SCHEMAS=ppolicy"
		"-e SLAPD_ADDITIONAL_MODULES=ppolicy"
		"-p 10389:389"
	)

	if [ -n "$1" ]; then
		case "$1" in
			'recreate'|'run'|'start')
				dockercontainer "$1" "${containername}" "${dockerimage}" "${containercmd}" "${containeroptions[@]}";;
			*)
				dockercontainer "$1" "${containername}" "${@:2:${#}}";;
		esac
	else
		dockerutil usage_display ${FUNCNAME[0]} "$(dockertemplate template_usage)"
	fi
}

#Global Variables
ldt_repo_dir="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && git rev-parse --show-toplevel)"

#External Functions
dockercontainer() {
	# @description reference dockercontainer to utilize it's functions
	# @output None

	local scriptpath="${ldt_repo_dir}/docker/dockercontainer"

	if [ -f "${scriptpath}" ]; then
		${scriptpath} "$@"
	else
		echo "Error: Could not load dockercontainer"
		return 1
	fi
}

dockertemplate() {
	# @description reference dockertemplate to utilize it's functions
	# @output None

	local scriptpath="${ldt_repo_dir}/docker/dockertemplate"

	if [ -f "${scriptpath}" ]; then
		${scriptpath} "$@"
	else
		echo "Error: Could not load dockertemplate"
		return 1
	fi
}

dockerutil() {
	# @description reference dockerutil to utilize it's functions
	# @output None

	local scriptpath="${ldt_repo_dir}/docker/dockerutil"

	if [ -f "${scriptpath}" ]; then
		${scriptpath} "$@"
	else
		echo "Error: Could not load dockerutil"
		return 1
	fi
}

verify_external_functions() {
	# @description check if external functions can be loaded, or else exit the script
	# @output None

	if !(dockercontainer > /dev/null); then dockercontainer; exit 1; fi
	if !(dockertemplate > /dev/null); then dockercontainer; exit 1; fi
	if !(dockerutil > /dev/null); then dockerutil; exit 1; fi
}

#Main
if [ "$0" = "${BASH_SOURCE}" ]; then
	if [ "${LDT_DEBUG}" == "1" ]; then
		verify_external_functions
	fi
	
	dockeropenldap "${@}"

	exit $?
fi