#!/bin/bash
#
# docker template for Elasticsearch 6.1.3
# Hostname: docker-container-ip
# Port: 9200
# Transport-Port: 9300
#
# Notes:
#     Removed docker port forwarding to host, use container's IP directly instead
#         Elasticsearch throws ReceiveTimeoutTransportException if we use localhost:9300 for the transport address

#Core Function
dockerelasticsearch6() {
	# @description create a docker container for Elasticsearch 6.1.3
	# @param $1 available commands listed in usages
	# @param $... additional parameters based on inital command used
	# @output varies, depending on the command used

	local dockerimage="docker.elastic.co/elasticsearch/elasticsearch:6.1.3"
	local containername="ldt_elasticsearch_6"
	local containercmd=""
	local containeroptions=(
		"-e discovery.type=single-node"
		"-e cluster.name=LiferayElasticsearchCluster"
		"-e network.host=0.0.0.0"
		"-e http.cors.enabled=true"
		"-e http.cors.allow-origin=*"
		"-e http.cors.allow-headers=X-Requested-With,Content-Type,Content-Length,X-User"
		"-e path.repo=/usr/share/elasticsearch/data/repo"
		"-p 9200:9200"
		"-p 9300:9300"
	)

	if [ -n "$1" ]; then
		case "$1" in
			'recreate'|'run'|'start')
				local init_elastic

				if [ "$1" == 'recreate' ] || (! dockercontainer 'exists' "${containername}"); then
					init_elastic=1
				fi

				dockercontainer "$1" "${containername}" "${dockerimage}" "${containercmd}" "${containeroptions[@]}"

				if [ "${init_elastic}" == "1" ]; then
					echo 'Note: providing some time for elasticsearch to startup before installing plugins'
					sleep 5

					dockercontainer exec "${containername}" ./bin/elasticsearch-plugin install analysis-icu
					dockercontainer exec "${containername}" ./bin/elasticsearch-plugin install analysis-kuromoji
					dockercontainer exec "${containername}" ./bin/elasticsearch-plugin install analysis-smartcn
					dockercontainer exec "${containername}" ./bin/elasticsearch-plugin install analysis-stempel					

					echo 'Note: restarting elasticsearch..'
					dockerelasticsearch6 'restart'

				fi;;
			*)
				dockercontainer "$1" "${containername}" "${@:2:${#}}";;
		esac
	else
		dockerutil usage_display ${FUNCNAME[0]} "$(dockertemplate template_usage)"
	fi
}

#Global Variables
ldt_repo_dir="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && git rev-parse --show-toplevel)"

#External Functions
dockercontainer() {
	# @description reference dockercontainer to utilize it's functions
	# @output None

	local scriptpath="${ldt_repo_dir}/docker/dockercontainer"

	if [ -f "${scriptpath}" ]; then
		${scriptpath} "$@"
	else
		echo "Error: Could not load dockercontainer"
		return 1
	fi
}

dockertemplate() {
	# @description reference dockertemplate to utilize it's functions
	# @output None

	local scriptpath="${ldt_repo_dir}/docker/dockertemplate"

	if [ -f "${scriptpath}" ]; then
		${scriptpath} "$@"
	else
		echo "Error: Could not load dockertemplate"
		return 1
	fi
}

dockerutil() {
	# @description reference dockerutil to utilize it's functions
	# @output None

	local scriptpath="${ldt_repo_dir}/docker/dockerutil"

	if [ -f "${scriptpath}" ]; then
		${scriptpath} "$@"
	else
		echo "Error: Could not load dockerutil"
		return 1
	fi
}

verify_external_functions() {
	# @description check if external functions can be loaded, or else exit the script
	# @output None

	if !(dockercontainer > /dev/null); then dockercontainer; exit 1; fi
	if !(dockertemplate > /dev/null); then dockercontainer; exit 1; fi
	if !(dockerutil > /dev/null); then dockerutil; exit 1; fi
}

#Main
if [ "$0" = "${BASH_SOURCE}" ]; then
	if [ "${LDT_DEBUG}" == "1" ]; then
		verify_external_functions
	fi

	dockerelasticsearch6 "${@}"

	exit $?
fi