#!/bin/bash
#
# docker template for nginx
# host: localhost
# port: 8081 (configured via -p 8081:80)
# directory: ./html (configured via -v $(dirname ${BASH_SOURCE[0]})/html:/usr/share/nginx/html:ro)
#   can be used for adding custom web files

#Functions
dockernginx() {
	# @description create a docker container for nginx
	# @param $1 available commands listed in usages
	# @param $... additional parameters based on inital command used
	# @output varies, depending on the command used

	local dockerimage="nginx:1.13.6-alpine"
	local containername="ldt_nginx"
	local containercmd=""
	local containeroptions=(
		"-v $(dirname ${BASH_SOURCE[0]})/html:/usr/share/nginx/html:ro"
		"-p 8081:80"
	)

	if [ -n "$1" ]; then
		case "$1" in
			'recreate'|'run'|'start')
				dockercontainer "$1" "${containername}" "${dockerimage}" "${containercmd}" "${containeroptions[@]}";;
			*)
				dockercontainer "$1" "${containername}" "${@:2:${#}}";;
		esac
	else
		echo "Usage: ${FUNCNAME[0]} {$(usage_options_formatted ${dockercontainer_options[@]} ${dockerbasecontainer_options[@]})}"
	fi
}

init_dockercontainer() {
	# @description source dockercontainer to make it's functions available
	# @output None

	local repodir="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && git rev-parse --show-toplevel)"
	local scriptpath="${repodir}/docker/dockercontainer"

	if [ -f "${scriptpath}" ]; then
		. ${scriptpath}
	else
		echo "Error: Could not load dockercontainer"
		exit 1
	fi
}

#Main
init_dockercontainer

if [ "$0" = "${BASH_SOURCE}" ]; then
	dockernginx "${@}"

	exit $?
fi