#!/bin/bash
#
# docker template for SQL Server
# Username: SA
# Password: <YourStrong!Passw0rd> (configured via -e MSSQL_SA_PASSWORD=\<YourStrong!Passw0rd\>)
# Hostname: localhost
# Port: 1433 (configured via -p 1433:1433)
# JDBC URL Example: jdbc:sqlserver://localhost:1433
#
# Note: Make sure to configure Docker to allocate at least 4GB of ram (Mac OS/Windows)
#   Info: https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker#requirements
#	Docker for mac: https://docs.docker.com/docker-for-mac/#memory
#	Docker for Windows: https://docs.docker.com/docker-for-windows/#advanced
#
# References:
# https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker
# https://docs.microsoft.com/en-us/sql/relational-databases/security/password-policy1

#Core Function
dockersqlserver() {
	# @description create a docker container for SQL Server
	# @param $1 available commands listed in usages
	# @param $... additional parameters based on inital command used
	# @output varies, depending on the command used

	local dockerimage="microsoft/mssql-server-linux:2017-latest"
	local containername="ldt_sqlserver"
	local containercmd=""
	local containeroptions=(
		"-e ACCEPT_EULA=Y"
		"-e MSSQL_SA_PASSWORD=\<YourStrong!Passw0rd\>"
		"-p 1433:1433"
	)

	if [ -n "$1" ]; then
		case "$1" in
			'recreate'|'run'|'start')
				dockercontainer "$1" "${containername}" "${dockerimage}" "${containercmd}" "${containeroptions[@]}";;
			*)
				dockercontainer "$1" "${containername}" "${@:2:${#}}";;
		esac
	else
		dockerutil usage_display ${FUNCNAME[0]} "$(dockertemplate template_usage)"
	fi
}

#Global Variables
ldt_repo_dir="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && git rev-parse --show-toplevel)"

#External Functions
dockercontainer() {
	# @description reference dockercontainer to utilize it's functions
	# @output None

	local scriptpath="${ldt_repo_dir}/docker/dockercontainer"

	if [ -f "${scriptpath}" ]; then
		${scriptpath} "$@"
	else
		echo "Error: Could not load dockercontainer"
		return 1
	fi
}

dockertemplate() {
	# @description reference dockertemplate to utilize it's functions
	# @output None

	local scriptpath="${ldt_repo_dir}/docker/dockertemplate"

	if [ -f "${scriptpath}" ]; then
		${scriptpath} "$@"
	else
		echo "Error: Could not load dockertemplate"
		return 1
	fi
}

dockerutil() {
	# @description reference dockerutil to utilize it's functions
	# @output None

	local scriptpath="${ldt_repo_dir}/docker/dockerutil"

	if [ -f "${scriptpath}" ]; then
		${scriptpath} "$@"
	else
		echo "Error: Could not load dockerutil"
		return 1
	fi
}

verify_external_functions() {
	# @description check if external functions can be loaded, or else exit the script
	# @output None

	if !(dockercontainer > /dev/null); then dockercontainer; exit 1; fi
	if !(dockertemplate > /dev/null); then dockercontainer; exit 1; fi
	if !(dockerutil > /dev/null); then dockerutil; exit 1; fi
}

#Main
if [ "$0" = "${BASH_SOURCE}" ]; then
	verify_external_functions
	
	dockersqlserver "${@}"

	exit $?
fi